import { readFile } from "node:fs/promises";
import { query } from "../db.js";
import { config } from "../config.js";
import { sendEmail } from "./redi-api.js";
import {
  generateCourseReport,
  generateAllDailyReports,
  markdownToHtml,
} from "./report-generator.js";

interface CourseInfo {
  course_name: string;
  course_date: string;
}

export async function sendReport(courseId: string): Promise<void> {
  console.log(`Generating and sending report for course: ${courseId}`);

  const { markdownPath } = await generateCourseReport(courseId);

  const markdown = await readFile(markdownPath, "utf-8");
  const htmlBody = wrapHtml(markdownToHtml(markdown));

  const courseResult = await query<CourseInfo>(
    `SELECT course_name, course_date::text FROM courses WHERE course_id = $1`,
    [courseId]
  );
  if (courseResult.rows.length === 0) {
    throw new Error(`Course not found: ${courseId}`);
  }
  const course = courseResult.rows[0]!;

  const subject = `Course Outcome Report - ${course.course_name} - ${course.course_date}`;

  await sendEmail(config.reportEmailTo, subject, htmlBody, {
    importance: "Normal",
  });

  console.log(`Report email sent for course: ${course.course_name}`);
}

export async function sendAllDailyReports(): Promise<number> {
  console.log("Generating and sending all daily reports");

  const reports = await generateAllDailyReports();
  let sent = 0;

  for (const report of reports) {
    try {
      const markdown = await readFile(report.markdownPath, "utf-8");
      const htmlBody = wrapHtml(markdownToHtml(markdown));

      const courseResult = await query<CourseInfo>(
        `SELECT course_name, course_date::text FROM courses WHERE course_id = $1`,
        [report.courseId]
      );
      if (courseResult.rows.length === 0) continue;
      const course = courseResult.rows[0]!;

      const subject = `Course Outcome Report - ${course.course_name} - ${course.course_date}`;

      await sendEmail(config.reportEmailTo, subject, htmlBody, {
        importance: "Normal",
      });

      sent++;
      console.log(`Sent report for: ${course.course_name}`);
    } catch (err) {
      console.error(
        `Failed to send report for course ${report.courseId}:`,
        err
      );
    }
  }

  console.log(`Sent ${sent}/${reports.length} daily reports`);
  return sent;
}

function wrapHtml(body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
  h1 { color: #1a365d; border-bottom: 2px solid #1a365d; padding-bottom: 8px; }
  h2 { color: #2a4365; margin-top: 24px; }
  h3 { color: #2c5282; margin-top: 16px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
  th { background: #edf2f7; font-weight: bold; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
  strong { color: #1a202c; }
  ul { margin: 8px 0; }
  li { margin: 4px 0; }
  p { margin: 4px 0; }
</style>
</head>
<body>
${body}
<br>
<p style="color: #718096; font-size: 12px;">
  This report was generated by the REdI Assessment System.
  CSV version saved to the data volume.
</p>
</body>
</html>`;
}
