import { readFile } from "node:fs/promises";
import { query } from "../db.js";
import { config } from "../config.js";
import { sendEmail } from "./redi-api.js";
import {
  generateCourseReport,
  generateAllDailyReports,
  markdownToHtml,
} from "./report-generator.js";

interface CourseInfo {
  course_name: string;
  course_date: string;
}

export async function sendReport(courseId: string): Promise<void> {
  console.log(`Generating and sending report for course: ${courseId}`);

  const { markdownPath } = await generateCourseReport(courseId);

  const markdown = await readFile(markdownPath, "utf-8");
  const htmlBody = wrapHtml(markdownToHtml(markdown));

  const courseResult = await query<CourseInfo>(
    `SELECT course_name, course_date::text FROM courses WHERE course_id = $1`,
    [courseId]
  );
  if (courseResult.rows.length === 0) {
    throw new Error(`Course not found: ${courseId}`);
  }
  const course = courseResult.rows[0]!;

  const subject = `[REdI Assessment] Course Outcome Report - ${course.course_name} - ${course.course_date}`;

  await sendEmail(config.reportEmailTo, subject, htmlBody, {
    importance: "Normal",
  });

  console.log(`Report email sent for course: ${course.course_name}`);
}

export async function sendAllDailyReports(): Promise<number> {
  console.log("Generating and sending all daily reports");

  const reports = await generateAllDailyReports();
  let sent = 0;

  for (const report of reports) {
    try {
      const markdown = await readFile(report.markdownPath, "utf-8");
      const htmlBody = wrapHtml(markdownToHtml(markdown));

      const courseResult = await query<CourseInfo>(
        `SELECT course_name, course_date::text FROM courses WHERE course_id = $1`,
        [report.courseId]
      );
      if (courseResult.rows.length === 0) continue;
      const course = courseResult.rows[0]!;

      const subject = `[REdI Assessment] Course Outcome Report - ${course.course_name} - ${course.course_date}`;

      await sendEmail(config.reportEmailTo, subject, htmlBody, {
        importance: "Normal",
      });

      sent++;
      console.log(`Sent report for: ${course.course_name}`);
    } catch (err) {
      console.error(
        `Failed to send report for course ${report.courseId}:`,
        err
      );
    }
  }

  console.log(`Sent ${sent}/${reports.length} daily reports`);
  return sent;
}

function wrapHtml(body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; margin: 0; padding: 0; color: #333; }
  .header { background: #1B3A5F; color: white; padding: 20px; border-top: 4px solid #E55B64; }
  .header h1 { margin: 0; font-size: 24px; font-weight: bold; }
  .header p { margin: 4px 0 0 0; font-size: 14px; color: #E5E7EB; }
  .content { padding: 20px; }
  h1 { color: #1B3A5F; border-bottom: 2px solid #E55B64; padding-bottom: 8px; }
  h2 { color: #1B3A5F; margin-top: 24px; }
  h3 { color: #2c5282; margin-top: 16px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
  th { background: #edf2f7; font-weight: bold; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
  strong { color: #1a202c; }
  ul { margin: 8px 0; }
  li { margin: 4px 0; }
  p { margin: 4px 0; }
</style>
</head>
<body>
<div class="header">
  <h1>REdI Assessment System</h1>
  <p>Resuscitation Education Initiative - Queensland Health</p>
</div>
<div class="content">
${body}
<br>
<p style="color: #718096; font-size: 12px;">
  This report was generated by the REdI Assessment System.
  CSV version saved to the data volume.
</p>
<hr style="margin: 24px 0; border: none; border-top: 1px solid #e5e7eb;" />
<p style="font-size: 11px; color: #6b7280; line-height: 1.5;">
  This email contains confidential information related to competency assessments
  conducted under the Resuscitation Education Initiative (REdI). It is intended solely
  for the named recipient(s). If you have received this email in error, please notify
  the sender and delete it immediately. This data is managed in accordance with the
  <em>Information Privacy Act 2009</em> (Qld) and Queensland Health information
  security policies. Do not forward or share assessment data outside authorised channels.
</p>
</div>
</body>
</html>`;
}
